### PR TITLE
Add control_transfer implementation

### LINKED ISSUE #1: control_transfer not implemented
`control_transfer` is not yet implemented in InterfaceHandle althought the binding is present in [libusb-sys](https://github.com/dcuddeback/libusb-sys/blob/master/src/lib.rs#L271).

Any plan on that? Do you accept PR on this?

[Slightly OT but related]: xxx_transfer should have been implemented on DeviceHandle, no? I agree it makes sense on InterfaceHandle but

### PR DESCRIPTION
**Pull request by nibua-r**
Fix #1

### CODE REVIEW

**Comment by dcuddeback** [comment]
@nibua-r This looks good. :+1: 

In #1, you mentioned that it needs tests. Unit tests for the `ControlRequest` struct would be helpful, but I'd be okay merging this PR without them too. I plan to add functionality for string descriptors based on your work in this PR. I'll update [examples/read_device.rs](https://github.com/dcuddeback/libusb-rs/blob/master/examples/read_device.rs) to read string descriptors when I add that feature. I think that will be enough to test the control transfer, so you don't need to add anything for that in this PR. Most of the heavy logic is in the C library anyway, which I trust to be correct.

If you don't mind, I'd appreciate it if you'd squash the commits into a single commit to reduce the number of intermediate commits. You can do that with `git rebase -i master` and then changing `pick` to `fixup` for all but the first commit.

Thanks again for all your work on this. I really appreciate the help. I've been wanting to implement string descriptors for a while, so I'm particularly excited to see this merged. :)

**Comment by nibua-r** [comment]
Squash done! :+1:

**Comment by nibua-r** [comment]
String descriptor features will be of great value to me! Would like any help on this?

**Comment by dcuddeback** [comment]
@nibua-r Thanks! I'll see how far I get with the string descriptors and then let you know.

**Comment by dcuddeback** [comment]
@nibua-r I finished string descriptors this weekend and published v0.1.1 to crates.io.

**Pull request merged**
